### ISSUE TITLE
testthat tests

### ISSUE THREAD

**Issue by ericbair-sciome** [Spatiotemporal-Exposures-and-Toxicology/PrestoGP#20]
I will work on create testthat tests for all core PrestoGP functions.

**Comment by ericbair-sciome** [comment]
I'm going to go ahead and close this issue with the latest update for the time being. We are still short of 100% coverage, but I believe that all of the critical code is covered at this point. We can come back and try to get closer to 100% coverage at a later date.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@ericbair-sciome  @shail-choksi @sciome-bot 

Fantastic - I will look at the updates and pull request ASAP.
