### ISSUE TITLE
Code for univariate models needs to be updated

### ISSUE THREAD

**Issue by ericbair-sciome** [Spatiotemporal-Exposures-and-Toxicology/PrestoGP#41]
The code for univariate models is not working. I believe this is due to changes that we have made to the multivariate model code that broke the older univariate code. I am going to work on updating that code so that it works again.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@ericbair-sciome Thanks for opening this issue - an important one to resolve clearly.

**Comment by ericbair-sciome** [comment]
This is fixed in the latest update.
