### ISSUE TITLE
Testing for binomial models

### ISSUE THREAD

**Issue by ericbair-sciome** [Spatiotemporal-Exposures-and-Toxicology/PrestoGP#50]
I have implemented the ability to fit binomial models on my branch (which we will push to GitHub very soon), but I have done zero testing to confirm that the code works. At some point, we need to write some simulations and eventually testthat tests to confirm that binomial regression models are working the way that we expect.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@ericbair-sciome that is all good - no nee to go deeper into this. You can push that and provide to the DLH folks.

**Comment by ericbair-sciome** [comment]
I would be inclined to keep this open for now even if it is not a priority in the near future. Someone should look at this at some point, even if it is a version 2.0 thing. I just opened the issue so that I don't forget about it.
